# Test Profile Configuration

spring:
  # Datasource Configuration for Test (H2)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Redis Configuration for Test
  data:
    redis:
      host: localhost
      port: 6379

# JWT Configuration for Test
jwt:
  secret: test-secret-key-for-testing-purposes-must-be-at-least-256-bits-which-is-32-bytes-or-64-hex-characters-0123456789abcdef
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

# Logging
logging:
  level:
    root: INFO
    me.onetwo.growsnap: DEBUG
